import streamlit as st
import requests

NAIVE_API    = "http://localhost:8000"
ADVANCED_API = "http://localhost:8001"

st.set_page_config(
    page_title="RAG Comparison",
    page_icon="⚡",
    layout="wide"
)

st.title("⚡ Naive RAG vs Advanced RAG")
st.caption("Side-by-side comparison — same question, different pipeline")

# ── Sidebar ──────────────────────────────────────────────
with st.sidebar:
    st.header("Pipeline Info")
    
    st.subheader("🔵 Naive RAG")
    st.write("- Fixed-size chunking (512 token)")
    st.write("- Pure vector search")
    st.write("- No reranking")
    st.write("- Direct query embedding")
    
    st.divider()
    
    st.subheader("🟢 Advanced RAG")
    st.write("- Semantic chunking")
    st.write("- Hybrid search (BM25 + Vector)")
    st.write("- Cross-Encoder reranking")
    st.write("- HyDE query transformation")
    
    st.divider()
    
    st.write("**Example questions:**")
    examples = [
        "What is Retrieval-Augmented Generation?",
        "What are the limitations of Naive RAG?",
        "How does reranking improve RAG performance?",
        "What is the difference between sparse and dense retrieval?",
    ]
    for ex in examples:
        if st.button(ex, use_container_width=True):
            st.session_state["question"] = ex

# ── Input ─────────────────────────────────────────────────
question = st.text_input(
    "Ask a question:",
    value=st.session_state.get("question", ""),
    placeholder="e.g. What are the main components of a RAG pipeline?"
)

col_run1, col_run2, col_run3 = st.columns([1, 1, 4])
with col_run1:
    run_both    = st.button("⚡ Compare Both", type="primary")
with col_run2:
    run_naive   = st.button("🔵 Naive Only")

# ── Helper: call API ──────────────────────────────────────
def call_naive(q: str) -> dict | None:
    """
    Call Naive RAG API on port 8000.
    Return None if the API doesn't work.
    """
    try:
        resp = requests.post(
            f"{NAIVE_API}/query",
            json={"question": q},
            timeout=60
        )
        resp.raise_for_status()
        return resp.json()
    except requests.exceptions.ConnectionError:
        return None
    except Exception as e:
        st.error(f"Naive RAG error: {e}")
        return None


def call_advanced(q: str) -> dict | None:
    """
    Call Advanced RAG API on port 8001.
    Return None if the API doesn't work.
    """
    try:
        resp = requests.post(
            f"{ADVANCED_API}/query",
            json={"question": q},
            timeout=120  # Advanced slower due to HyDE + reranking
        )
        resp.raise_for_status()
        return resp.json()
    except requests.exceptions.ConnectionError:
        return None
    except Exception as e:
        st.error(f"Advanced RAG error: {e}")
        return None


# ── Main: Compare Both ────────────────────────────────────
if run_both and question:
    st.divider()
    
    # Dua kolom side by side
    col_naive, col_advanced = st.columns(2)
    
    # ── Kolom Kiri: Naive RAG ──────────────────────────
    with col_naive:
        st.subheader("🔵 Naive RAG")
        st.caption("Port 8000 — Fixed chunking, pure vector search")
        
        with st.spinner("Querying Naive RAG..."):
            naive_result = call_naive(question)
        
        if naive_result is None:
            st.error("Naive RAG API is not working. Please ensure port 8000 is active.")
        else:
            # Answer
            st.markdown("**Answer:**")
            st.write(naive_result["answer"])
            
            # Sources
            st.markdown(f"**Retrieved Sources ({len(naive_result['sources'])} chunks):**")
            for i, src in enumerate(naive_result["sources"], 1):
                with st.expander(f"Source {i} — {src['file']} (score: {src['score']})"):
                    st.write(src["text"])
    
    # ── Kolom Kanan: Advanced RAG ─────────────────────
    with col_advanced:
        st.subheader("🟢 Advanced RAG")
        st.caption("Port 8001 — Semantic chunking, hybrid search, reranking, HyDE")
        
        with st.spinner("Querying Advanced RAG (slower due to HyDE + reranking)..."):
            adv_result = call_advanced(question)
        
        if adv_result is None:
            st.error("Advanced RAG API is not working. Please ensure port 8001 is active.")
        else:
            # Answer
            st.markdown("**Answer:**")
            st.write(adv_result["answer"])
            
            # HyDE Hypothetical
            with st.expander("🔍 HyDE: Hypothetical Document (click to see)"):
                st.caption(
                    "This is generated by LLM before search — "
                    "not the final answer, but a 'bridge' to enrich query embedding."
                )
                st.write(adv_result["hypothetical"])
            
            # Sources
            st.markdown(f"**Retrieved Sources ({len(adv_result['sources'])} chunks):**")
            for i, src in enumerate(adv_result["sources"], 1):
                with st.expander(f"Source {i} — {src['file']} (score: {src['score']})"):
                    st.write(src["text"])
    
    # ── Comparison Summary ────────────────────────────
    st.divider()
    st.subheader("📊 Comparison Summary")
    
    if naive_result and adv_result:
        # Hitung diversity sources
        naive_files = set(s["file"] for s in naive_result["sources"])
        adv_files   = set(s["file"] for s in adv_result["sources"])
        
        # Hitung average score
        naive_scores = [s["score"] for s in naive_result["sources"] if s["score"]]
        adv_scores   = [s["score"] for s in adv_result["sources"] if s["score"]]
        
        naive_avg = sum(naive_scores) / len(naive_scores) if naive_scores else 0
        adv_avg   = sum(adv_scores) / len(adv_scores) if adv_scores else 0
        
        # Tampilkan dalam tabel
        col1, col2, col3 = st.columns(3)
        
        with col1:
            st.metric(
                label="Source Diversity (Naive)",
                value=f"{len(naive_files)} file(s)",
            )
            st.metric(
                label="Source Diversity (Advanced)",
                value=f"{len(adv_files)} file(s)",
                delta=f"+{len(adv_files) - len(naive_files)} file(s)"
                      if len(adv_files) > len(naive_files) else None
            )
        
        with col2:
            st.metric(
                label="Avg Chunk Score (Naive)",
                value=f"{naive_avg:.3f}"
            )
            st.metric(
                label="Avg Chunk Score (Advanced)",
                value=f"{adv_avg:.3f}",
                delta=f"{adv_avg - naive_avg:+.3f}"
            )
        
        with col3:
            st.markdown("**Pipeline Steps:**")
            st.write("Naive: embed → search → generate")
            st.write("Advanced: HyDE → hybrid search → rerank → generate")


# ── Main: Naive Only ──────────────────────────────────────
elif run_naive and question:
    st.divider()
    st.subheader("🔵 Naive RAG Result")
    
    with st.spinner("Querying..."):
        naive_result = call_naive(question)         
    
    if naive_result is None:
        st.error("Naive RAG API is not working. Please ensure port 8000 is active.")
    else:
        st.markdown("**Answer:**")
        st.write(naive_result["answer"])
        
        st.markdown(f"**Sources ({len(naive_result['sources'])} chunks):**")
        for i, src in enumerate(naive_result["sources"], 1):
            with st.expander(f"Source {i} — {src['file']} (score: {src['score']})"):
                st.write(src["text"])